{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "terminal-tablet",
    "version": "1.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpsdk-cpcomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-1.0.21.aar",
          "url": "terminal-tablet-1.0.21.aar",
          "size": 103958,
          "sha512": "2210eedee4716660d2678bfa1d1cba7f6c90b645b71f36d87a33db7e4281e40594fa9a478035c68a4f0e13a8538e8bd49080039973c8b4b98abea5fc8beee4a7",
          "sha256": "859e4cc25b385b03c8f5022ffb064b96644b0d644192f58df2d37910ef746ac5",
          "sha1": "fe6de8af34fa884701a5de417b3dac6659485ee2",
          "md5": "ab4805ff3842a2c563c481cfa031ac4b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpsdk-cpcomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-1.0.21.aar",
          "url": "terminal-tablet-1.0.21.aar",
          "size": 103958,
          "sha512": "2210eedee4716660d2678bfa1d1cba7f6c90b645b71f36d87a33db7e4281e40594fa9a478035c68a4f0e13a8538e8bd49080039973c8b4b98abea5fc8beee4a7",
          "sha256": "859e4cc25b385b03c8f5022ffb064b96644b0d644192f58df2d37910ef746ac5",
          "sha1": "fe6de8af34fa884701a5de417b3dac6659485ee2",
          "md5": "ab4805ff3842a2c563c481cfa031ac4b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "terminal-tablet-1.0.21-javadoc.jar",
          "url": "terminal-tablet-1.0.21-javadoc.jar",
          "size": 407450,
          "sha512": "9ffd49f57fc675c9c4c2bdfee2cdf3e14f39ad334f14aafc158f3e33f6d34976e54aa05e0fa714d8b01df17597e492e7373fcc328dcf148c65f7d7487fdb0a0a",
          "sha256": "e3ae70d91739c4eb8335f2197f71721d6acceef9d39a881dfc6702c95ef2716f",
          "sha1": "aaa8fa5cf8f81670d6aa3bb20f50b25b037a2121",
          "md5": "ee300492fb3e44879cebf05ae01951f3"
        }
      ]
    }
  ]
}
