{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "rkcamera",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia.ipcam",
          "version": {
            "requires": "2.0.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "rkcamera-1.1.1.aar",
          "url": "rkcamera-1.1.1.aar",
          "size": 103867,
          "sha512": "6f1ddccc9405f7225fc6a56259bae8ab178ddba19a7314a3b9d185c9bf2b35c5efa3082a88bbe8cc2aa1c47da613bd968cbf0102fc85ee32c6d89ade2f8f93c0",
          "sha256": "3d7f6481a26addbed791622d324aafebac80e1853890955686ba12bf4adbe47a",
          "sha1": "8826d93af0272e0c8701fc872b0004aadf6ae19b",
          "md5": "e09db9b000b2229b5b257d76a3b24058"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.19.1"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia.ipcam",
          "version": {
            "requires": "2.0.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "rkcamera-1.1.1.aar",
          "url": "rkcamera-1.1.1.aar",
          "size": 103867,
          "sha512": "6f1ddccc9405f7225fc6a56259bae8ab178ddba19a7314a3b9d185c9bf2b35c5efa3082a88bbe8cc2aa1c47da613bd968cbf0102fc85ee32c6d89ade2f8f93c0",
          "sha256": "3d7f6481a26addbed791622d324aafebac80e1853890955686ba12bf4adbe47a",
          "sha1": "8826d93af0272e0c8701fc872b0004aadf6ae19b",
          "md5": "e09db9b000b2229b5b257d76a3b24058"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rkcamera-1.1.1-javadoc.jar",
          "url": "rkcamera-1.1.1-javadoc.jar",
          "size": 310353,
          "sha512": "8e81899b6e4051ec64ebd66724e207fee5e4f7ba41b8364ecc90c2ff3c8d7febf68191faaea7eb679b2a4bba9b01564afaccb9be0dc1793656fb9329955ea429",
          "sha256": "03d34db5258d7a9d7611e4f1704010d5f85679dfbc09188856391e4580b4df2f",
          "sha1": "bed13eb7629df18362259b8ce63356613e9d40d7",
          "md5": "ad41cdef684d98275697fc71938ccf69"
        }
      ]
    }
  ]
}
