{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "terminal-tablet",
    "version": "1.0.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpsdk-cpcomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-1.0.19.aar",
          "url": "terminal-tablet-1.0.19.aar",
          "size": 103948,
          "sha512": "b8fd993013911d738142a545dbd0f2101e73e3434063dbf9007a474fd2c2dc05ab6ce02833492121de684bdeb5fdd858b848b9147df5273255983dafd0a03d2c",
          "sha256": "38499a94ce7e7d0d0d7de63f2aad553ce271f48741c0a7a4f61d0a77af8509a0",
          "sha1": "0a53b38131127e71b561801cbc89a0e70e4eeb77",
          "md5": "b0b394487d78eec0d93db4df7e10726b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpsdk-cpcomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-1.0.19.aar",
          "url": "terminal-tablet-1.0.19.aar",
          "size": 103948,
          "sha512": "b8fd993013911d738142a545dbd0f2101e73e3434063dbf9007a474fd2c2dc05ab6ce02833492121de684bdeb5fdd858b848b9147df5273255983dafd0a03d2c",
          "sha256": "38499a94ce7e7d0d0d7de63f2aad553ce271f48741c0a7a4f61d0a77af8509a0",
          "sha1": "0a53b38131127e71b561801cbc89a0e70e4eeb77",
          "md5": "b0b394487d78eec0d93db4df7e10726b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "terminal-tablet-1.0.19-javadoc.jar",
          "url": "terminal-tablet-1.0.19-javadoc.jar",
          "size": 407450,
          "sha512": "9ffd49f57fc675c9c4c2bdfee2cdf3e14f39ad334f14aafc158f3e33f6d34976e54aa05e0fa714d8b01df17597e492e7373fcc328dcf148c65f7d7487fdb0a0a",
          "sha256": "e3ae70d91739c4eb8335f2197f71721d6acceef9d39a881dfc6702c95ef2716f",
          "sha1": "aaa8fa5cf8f81670d6aa3bb20f50b25b037a2121",
          "md5": "ee300492fb3e44879cebf05ae01951f3"
        }
      ]
    }
  ]
}
