{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "terminal-tablet",
    "version": "1.0.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpsdk-cpcomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-1.0.26.aar",
          "url": "terminal-tablet-1.0.26.aar",
          "size": 116139,
          "sha512": "b0e5654132c072d4736f24863598989daf23407566fb7c029892a4e25d4210efd34a640627a8a17521c8dedfadd7bcac92ed9e83f910face38ddc424f7c081eb",
          "sha256": "816b855ef6d6651f043630eeae7fd835831079ec4af69c9a3a5f7ea65750cff1",
          "sha1": "9a43108e5dd97d03b94a21895639d27788bcf86d",
          "md5": "73b8cdc562ff8bcf301bd74cc261b032"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpsdk-cpcomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-1.0.26.aar",
          "url": "terminal-tablet-1.0.26.aar",
          "size": 116139,
          "sha512": "b0e5654132c072d4736f24863598989daf23407566fb7c029892a4e25d4210efd34a640627a8a17521c8dedfadd7bcac92ed9e83f910face38ddc424f7c081eb",
          "sha256": "816b855ef6d6651f043630eeae7fd835831079ec4af69c9a3a5f7ea65750cff1",
          "sha1": "9a43108e5dd97d03b94a21895639d27788bcf86d",
          "md5": "73b8cdc562ff8bcf301bd74cc261b032"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "terminal-tablet-1.0.26-javadoc.jar",
          "url": "terminal-tablet-1.0.26-javadoc.jar",
          "size": 412280,
          "sha512": "077d6c46e23a3974fa7822b433dd067bb2c731815c92ddd1306531c66b72820217000a181360dd549fbfea64f1d623fc43d5db8fe276073ed1459e41060a7086",
          "sha256": "7a51007a0f161481dde81ef08d8f798d09ae94c3ab73f7324226b1d1402c5945",
          "sha1": "7eba23ffc924ebcf5f4317df6288b4c83d695f7b",
          "md5": "d4c7d0894bb46ff2aec73df70172ec94"
        }
      ]
    }
  ]
}
