{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib.cpdevice",
    "module": "apolloprocomm",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "apolloprocomm-1.0.3.aar",
          "url": "apolloprocomm-1.0.3.aar",
          "size": 10389,
          "sha512": "605ccd6a46a9166f3ca036b252841d0935c518e2e538125695c6d8131d502802a7f7b0c8312a64fd957d06dcb2dd8a62b413091a001cac4b632490902e813005",
          "sha256": "9979a00d5eed4bbc398ab76637999c33789fd8897182254a51bde9623306dd01",
          "sha1": "f396dcd524da3179330fa964395e135710de3d38",
          "md5": "a62fc829580d4b1d737b5b23f959199b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "apolloprocomm-1.0.3.aar",
          "url": "apolloprocomm-1.0.3.aar",
          "size": 10389,
          "sha512": "605ccd6a46a9166f3ca036b252841d0935c518e2e538125695c6d8131d502802a7f7b0c8312a64fd957d06dcb2dd8a62b413091a001cac4b632490902e813005",
          "sha256": "9979a00d5eed4bbc398ab76637999c33789fd8897182254a51bde9623306dd01",
          "sha1": "f396dcd524da3179330fa964395e135710de3d38",
          "md5": "a62fc829580d4b1d737b5b23f959199b"
        }
      ]
    }
  ]
}
