{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib.cpdevice",
    "module": "apolloprocomm",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "apolloprocomm-1.0.3.aar",
          "url": "apolloprocomm-1.0.3.aar",
          "size": 10060,
          "sha512": "f91499f16ad049e186f07c821a48ce8e7a18ad812af3518ec480ef9e4628abbfd8bf8bda576784f74bc1548f00a6832a22c4b6ad05386d71fb735030b10e4e04",
          "sha256": "75065c21b448204a4d07a554d85b0c0767b89c65c5fe39c263b2177afd5d8aea",
          "sha1": "6979506b420994f253cd121e4a2e3a0e156b3f3b",
          "md5": "8018498a50fe7e7e0f628964e579ffee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "apolloprocomm-1.0.3.aar",
          "url": "apolloprocomm-1.0.3.aar",
          "size": 10060,
          "sha512": "f91499f16ad049e186f07c821a48ce8e7a18ad812af3518ec480ef9e4628abbfd8bf8bda576784f74bc1548f00a6832a22c4b6ad05386d71fb735030b10e4e04",
          "sha256": "75065c21b448204a4d07a554d85b0c0767b89c65c5fe39c263b2177afd5d8aea",
          "sha1": "6979506b420994f253cd121e4a2e3a0e156b3f3b",
          "md5": "8018498a50fe7e7e0f628964e579ffee"
        }
      ]
    }
  ]
}
