{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "rkcamera",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "rkcamera-1.0.4.aar",
          "url": "rkcamera-1.0.4.aar",
          "size": 69420,
          "sha512": "ae126c75bc2ac38d858f71da91194f268126ca006547bcda138c9932991d83ba7daa569719ce861f2dab871be75dc3e168fe23233095b58b0e06d1167aad7c7d",
          "sha256": "b1ee00a5b85312c2ac2fdaf209bd9e0819e03b014448bfe001711b778c7ad9ce",
          "sha1": "f71124867413df4a622e800aa2cbb55946798aef",
          "md5": "3e75230b4157726117ce5329edd113d3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "rkcamera-1.0.4.aar",
          "url": "rkcamera-1.0.4.aar",
          "size": 69420,
          "sha512": "ae126c75bc2ac38d858f71da91194f268126ca006547bcda138c9932991d83ba7daa569719ce861f2dab871be75dc3e168fe23233095b58b0e06d1167aad7c7d",
          "sha256": "b1ee00a5b85312c2ac2fdaf209bd9e0819e03b014448bfe001711b778c7ad9ce",
          "sha1": "f71124867413df4a622e800aa2cbb55946798aef",
          "md5": "3e75230b4157726117ce5329edd113d3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rkcamera-1.0.4-javadoc.jar",
          "url": "rkcamera-1.0.4-javadoc.jar",
          "size": 294200,
          "sha512": "f265f4cdb7064ca84a1f1171fa252d47a83d98c362ba4c57ac46c42b0a31203d88c395acacf63aee4733eb72049ec121f1fab1cff35d9c966e47cb206d0a1632",
          "sha256": "4ac08b46d02cc6b516e0178eedbec0461d46b8c77b4bad76c6f02252d179b196",
          "sha1": "e2537b8d976bbad93457db119d02d6993a994997",
          "md5": "066f1c4e7d18b3a89987756cffda2d43"
        }
      ]
    }
  ]
}
