{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "terminal-tablet",
    "version": "2.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpcomm",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cputils",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-2.2.6.aar",
          "url": "terminal-tablet-2.2.6.aar",
          "size": 143367,
          "sha512": "da384ca1d975ac11a04a63de3c5ee2fb5e1f7ea1271d0d29b73ba97b36b44be8d2746808f6e396f5a36ee1a9db42b51bfb534bf28d454e3827d9bf01c179a674",
          "sha256": "ad69763d8d38785c8c3ccf25096581c4d4a1ab3c2b583491882ccedff205093b",
          "sha1": "18865930fb456c2f80302c21571f4e52d3cdcea3",
          "md5": "4a5dc03fa88a5374c5527a922e2e4ae3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpcomm",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cputils",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-2.2.6.aar",
          "url": "terminal-tablet-2.2.6.aar",
          "size": 143367,
          "sha512": "da384ca1d975ac11a04a63de3c5ee2fb5e1f7ea1271d0d29b73ba97b36b44be8d2746808f6e396f5a36ee1a9db42b51bfb534bf28d454e3827d9bf01c179a674",
          "sha256": "ad69763d8d38785c8c3ccf25096581c4d4a1ab3c2b583491882ccedff205093b",
          "sha1": "18865930fb456c2f80302c21571f4e52d3cdcea3",
          "md5": "4a5dc03fa88a5374c5527a922e2e4ae3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "terminal-tablet-2.2.6-javadoc.jar",
          "url": "terminal-tablet-2.2.6-javadoc.jar",
          "size": 450655,
          "sha512": "3734678844816590ec9df819d32c4777505f3dd7ef2d5f0f86b1aa9f71e8263d4dfb13081a6b08065ece1ec5439aa761c7c8852120904c43bf1411823c380ffd",
          "sha256": "1c8fe557ef831f304a9d41f67b2b579283aed28197c0ebb82297f59ea51f3daf",
          "sha1": "437f43e9d03ecb82840a89276d6f31c646ec7bfd",
          "md5": "11c59b2ca459a71ac6d6affc3670a164"
        }
      ]
    }
  ]
}
