{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "rkcamera",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "rkcamera-1.0.8.aar",
          "url": "rkcamera-1.0.8.aar",
          "size": 77306,
          "sha512": "9e8c29e1c1f6eb2edb332271ea6ee44a8a4538362948a9e114f5004c4c2d6bd4641efd8746a2080695fdbb408a8d1852c0e678b9ec95bd74d5ba741c70dcd3f7",
          "sha256": "9647bcd21ff6b8e43e84bba82a17e4fda1b37c922bbc9357359786ba0adcc5c2",
          "sha1": "c8d04e802a4e7372aa395ae5f23eae9438845d0e",
          "md5": "45a5c70f872f2ee6417fdf307fc8d355"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "rkcamera-1.0.8.aar",
          "url": "rkcamera-1.0.8.aar",
          "size": 77306,
          "sha512": "9e8c29e1c1f6eb2edb332271ea6ee44a8a4538362948a9e114f5004c4c2d6bd4641efd8746a2080695fdbb408a8d1852c0e678b9ec95bd74d5ba741c70dcd3f7",
          "sha256": "9647bcd21ff6b8e43e84bba82a17e4fda1b37c922bbc9357359786ba0adcc5c2",
          "sha1": "c8d04e802a4e7372aa395ae5f23eae9438845d0e",
          "md5": "45a5c70f872f2ee6417fdf307fc8d355"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rkcamera-1.0.8-javadoc.jar",
          "url": "rkcamera-1.0.8-javadoc.jar",
          "size": 288207,
          "sha512": "c920940ce1f95ac80389d0f99fc3f52510cc3eca27185952037589173d5b6e242157edd02b1fb245cd594989187607dc316b0e0f344f3d5e4fcfcbc23c857e80",
          "sha256": "5bd5af41e02d9cd0cadd21b3234049ca34f41f761196d59dea96f6ca7e69d10b",
          "sha1": "7084dbef74980aa48412d76d5e070ecb09d6114a",
          "md5": "fe00b680b0eade1a97c8e52a0eaf2cc4"
        }
      ]
    }
  ]
}
