{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "rkcamera",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "rkcamera-1.0.3.aar",
          "url": "rkcamera-1.0.3.aar",
          "size": 64190,
          "sha512": "c38ee178f5d2a68c9eeb4d8c58d3b4b9513e51550112204bdcbdd700522a5e18f49077fc3f69eb18f8c0e828ba9eb2ef2732f63757d833fc4a066ed60c589810",
          "sha256": "32b25a8c015a0492583e27cd1130515220ec2755ffd48ff24d1d65b0c03aaf32",
          "sha1": "51d0a2d565c378b31f9c305b22ab161aa9eed9b7",
          "md5": "43219322356a45b0700fd1977aac9519"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "rkcamera-1.0.3.aar",
          "url": "rkcamera-1.0.3.aar",
          "size": 64190,
          "sha512": "c38ee178f5d2a68c9eeb4d8c58d3b4b9513e51550112204bdcbdd700522a5e18f49077fc3f69eb18f8c0e828ba9eb2ef2732f63757d833fc4a066ed60c589810",
          "sha256": "32b25a8c015a0492583e27cd1130515220ec2755ffd48ff24d1d65b0c03aaf32",
          "sha1": "51d0a2d565c378b31f9c305b22ab161aa9eed9b7",
          "md5": "43219322356a45b0700fd1977aac9519"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rkcamera-1.0.3-javadoc.jar",
          "url": "rkcamera-1.0.3-javadoc.jar",
          "size": 294200,
          "sha512": "f265f4cdb7064ca84a1f1171fa252d47a83d98c362ba4c57ac46c42b0a31203d88c395acacf63aee4733eb72049ec121f1fab1cff35d9c966e47cb206d0a1632",
          "sha256": "4ac08b46d02cc6b516e0178eedbec0461d46b8c77b4bad76c6f02252d179b196",
          "sha1": "e2537b8d976bbad93457db119d02d6993a994997",
          "md5": "066f1c4e7d18b3a89987756cffda2d43"
        }
      ]
    }
  ]
}
