{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "terminal-tablet",
    "version": "2.2.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpcomm",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cputils",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-2.2.11.aar",
          "url": "terminal-tablet-2.2.11.aar",
          "size": 142431,
          "sha512": "7934c9c28ac1280b0f07f927231c45d681d764ef2d26f280ff459bed5930aaa5f8478d2a95fcc0e9dcc5bd13f25dce5f0fa72ba277213c02bcd4a1132ab3dac3",
          "sha256": "5eaaa8f2955d7b2e8c794e9e6bdf558818799a02b70cd563c4c0d5e388f59270",
          "sha1": "8195da23a9e25c4342d1412c400bd5ddbcb66db0",
          "md5": "ff4c26e0414ded6c6445e2adcaf6df70"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpcomm",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cputils",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-2.2.11.aar",
          "url": "terminal-tablet-2.2.11.aar",
          "size": 142431,
          "sha512": "7934c9c28ac1280b0f07f927231c45d681d764ef2d26f280ff459bed5930aaa5f8478d2a95fcc0e9dcc5bd13f25dce5f0fa72ba277213c02bcd4a1132ab3dac3",
          "sha256": "5eaaa8f2955d7b2e8c794e9e6bdf558818799a02b70cd563c4c0d5e388f59270",
          "sha1": "8195da23a9e25c4342d1412c400bd5ddbcb66db0",
          "md5": "ff4c26e0414ded6c6445e2adcaf6df70"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "terminal-tablet-2.2.11-javadoc.jar",
          "url": "terminal-tablet-2.2.11-javadoc.jar",
          "size": 450772,
          "sha512": "bd5611450cbdbb5bebed7018ac1dd6d1b47ed9cd5bc701220889326b9b608dd2a4be0a13e0af3e6dce2bdf88befb946f4a2806fc9682bc362079e10595eb7e64",
          "sha256": "046bdfa743e8e87f71786708df7445e0535b7d2d3320ca52c3e93dd61ffc12e8",
          "sha1": "1f7a0e3954a81bbed6a102274c55025ce946d2d5",
          "md5": "9521fba053670ca1d03f6cea9139a960"
        }
      ]
    }
  ]
}
