{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "terminal-tablet",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "springcomm",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-1.0.5.aar",
          "url": "terminal-tablet-1.0.5.aar",
          "size": 54994,
          "sha512": "97ae947ebd0fd3596f997b464981995d8c2c8c10330fb7788e4b6187b0be0032c7c99feadb528929b5bc86077657c3d3b1218287cca3800fc1260cd81af2f3a3",
          "sha256": "3567e840502fcf5537f2c93dab170154788bd8b414ce422eaf18a4d84d4aa298",
          "sha1": "55d7b56940cc1a2ed7c1b56cb1bbabcc89e7b898",
          "md5": "9a1a1b7334ef8885100c7813e151fedd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "springcomm",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-1.0.5.aar",
          "url": "terminal-tablet-1.0.5.aar",
          "size": 54994,
          "sha512": "97ae947ebd0fd3596f997b464981995d8c2c8c10330fb7788e4b6187b0be0032c7c99feadb528929b5bc86077657c3d3b1218287cca3800fc1260cd81af2f3a3",
          "sha256": "3567e840502fcf5537f2c93dab170154788bd8b414ce422eaf18a4d84d4aa298",
          "sha1": "55d7b56940cc1a2ed7c1b56cb1bbabcc89e7b898",
          "md5": "9a1a1b7334ef8885100c7813e151fedd"
        }
      ]
    }
  ]
}
