{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "rkcamera",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "rkcamera-1.0.1.aar",
          "url": "rkcamera-1.0.1.aar",
          "size": 37493,
          "sha512": "04a5c5b0bf1e371633532519d86142d08ca82def750453d915f98fa1d93ffd7d8f29a71da9f214c68668f180a79749f566b82a9103375554031a9e90ffd53f40",
          "sha256": "3a7e89824cd71f86fa1d7356ff11c855ea0d5eb766e589a4b10d1019876c5a79",
          "sha1": "3213c7598f0c0cd26ba3c36e911f9b450eac1d82",
          "md5": "2acd38584551ce39bd5d489b6b4763c4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "rkcamera-1.0.1.aar",
          "url": "rkcamera-1.0.1.aar",
          "size": 37493,
          "sha512": "04a5c5b0bf1e371633532519d86142d08ca82def750453d915f98fa1d93ffd7d8f29a71da9f214c68668f180a79749f566b82a9103375554031a9e90ffd53f40",
          "sha256": "3a7e89824cd71f86fa1d7356ff11c855ea0d5eb766e589a4b10d1019876c5a79",
          "sha1": "3213c7598f0c0cd26ba3c36e911f9b450eac1d82",
          "md5": "2acd38584551ce39bd5d489b6b4763c4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rkcamera-1.0.1-javadoc.jar",
          "url": "rkcamera-1.0.1-javadoc.jar",
          "size": 274981,
          "sha512": "1c411c74de3fc769896401af27cb809c1f02e40e56a9f275e7efde8aa41c45166783b426054b80455942704202ec0358976002e56e3fb868c683127c7283c024",
          "sha256": "a57c86dcbb72465f20017c5b84552ba4aca1beddf6ab5f96344b223008f99f18",
          "sha1": "0a61c54e1f1cd120ab4001ef75a44d2b79e08a83",
          "md5": "ebaf4776db7de56c5e7f39db42d778b8"
        }
      ]
    }
  ]
}
