{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "rkcamera",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia.ipcam",
          "version": {
            "requires": "2.0.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "rkcamera-1.1.3.aar",
          "url": "rkcamera-1.1.3.aar",
          "size": 106641,
          "sha512": "947ebe349db4790bd437a0b93093b9a1078759fcb68e085d9c685fa6221383110d5d2bf0212c9fef32eed3f3688d54cfa074b5ddeddc54c30135a8631076fd87",
          "sha256": "4322d8781c92cd606543d7f39fd604a2c7392896b309bce8c25f43719e3ed5c3",
          "sha1": "0c88c6e4ffcf47c5d98538839a2bc3d6afc2517f",
          "md5": "7f9384acf4fa0e7bc2e6e5ce0651abbb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.19.1"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia.ipcam",
          "version": {
            "requires": "2.0.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "rkcamera-1.1.3.aar",
          "url": "rkcamera-1.1.3.aar",
          "size": 106641,
          "sha512": "947ebe349db4790bd437a0b93093b9a1078759fcb68e085d9c685fa6221383110d5d2bf0212c9fef32eed3f3688d54cfa074b5ddeddc54c30135a8631076fd87",
          "sha256": "4322d8781c92cd606543d7f39fd604a2c7392896b309bce8c25f43719e3ed5c3",
          "sha1": "0c88c6e4ffcf47c5d98538839a2bc3d6afc2517f",
          "md5": "7f9384acf4fa0e7bc2e6e5ce0651abbb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rkcamera-1.1.3-javadoc.jar",
          "url": "rkcamera-1.1.3-javadoc.jar",
          "size": 310540,
          "sha512": "c81fddbae69419b648d949803a88695c68d070a9b61d6a2eaa5f1b4e99e3f5d11acc610e32c80c365ff3c7af33361e0f6c707384090f9bfafc41dc9cfb9725f6",
          "sha256": "d686c3b7d45b75556bfbf54062e6be954029bf0cfca9b80061c49bf25821ae3b",
          "sha1": "ca42d3826a9ba76ef023e7b665231ab087c453e4",
          "md5": "3596ca382fd0d37e653ca08caf6172ad"
        }
      ]
    }
  ]
}
