{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "terminal-tablet",
    "version": "1.0.34",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpsdk-cpcomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-1.0.34.aar",
          "url": "terminal-tablet-1.0.34.aar",
          "size": 120596,
          "sha512": "7bca781f0b8e45f439e1e34926245581cf1faa9e2f33cc40d4b5d79e3cf5cb56122b00baebe4d3aec37cc6bfd535894e340b783411201ebcaa0c296b993b0e44",
          "sha256": "dd7686c6c2bd0692e8201f340a92ea08dfc8120464b6f32e62facb4e725e90ab",
          "sha1": "9511389a36f34c1f1ef3103e8323b7cd8e149815",
          "md5": "81e06ec9789a030e555145fe20088fb4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpsdk-cpcomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-1.0.34.aar",
          "url": "terminal-tablet-1.0.34.aar",
          "size": 120596,
          "sha512": "7bca781f0b8e45f439e1e34926245581cf1faa9e2f33cc40d4b5d79e3cf5cb56122b00baebe4d3aec37cc6bfd535894e340b783411201ebcaa0c296b993b0e44",
          "sha256": "dd7686c6c2bd0692e8201f340a92ea08dfc8120464b6f32e62facb4e725e90ab",
          "sha1": "9511389a36f34c1f1ef3103e8323b7cd8e149815",
          "md5": "81e06ec9789a030e555145fe20088fb4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "terminal-tablet-1.0.34-javadoc.jar",
          "url": "terminal-tablet-1.0.34-javadoc.jar",
          "size": 421351,
          "sha512": "39256c3355b64c4a9fabcc74b8aeebbef9557f090da502270ba403ec0d7c3c2c9fcd13696cc3aba66f6bee4542c5ef7b427e8568f2e6d46a197049b1f900d020",
          "sha256": "9566fe6db62760541f3f0686e5fef60b72f66c639593b060c0e3c2e79f3a134f",
          "sha1": "504fc92383d22d50bdae98250a816627a8ded273",
          "md5": "2e3c1fd00efbe1d34ced96d6aa42366d"
        }
      ]
    }
  ]
}
