{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "terminal-tablet",
    "version": "1.0.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpsdk-cpcomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-1.0.31.aar",
          "url": "terminal-tablet-1.0.31.aar",
          "size": 116264,
          "sha512": "aa8f4e00ed48e5eec70db04b119c6f973428162b79de911598b89c167ad90be24356182fe1944d1137d64bca5707842ccd3f498b15594ca16949fbc033cd18c7",
          "sha256": "ef71c45e4355f16adbb9e081565fcc94960a9b1a6356b9121b746bd0346f6375",
          "sha1": "18d842bab4fb424d61c8eba8a755aa5124615f2c",
          "md5": "fbcf8d210524c94fe0038b292cfc32fc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpsdk-cpcomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-1.0.31.aar",
          "url": "terminal-tablet-1.0.31.aar",
          "size": 116264,
          "sha512": "aa8f4e00ed48e5eec70db04b119c6f973428162b79de911598b89c167ad90be24356182fe1944d1137d64bca5707842ccd3f498b15594ca16949fbc033cd18c7",
          "sha256": "ef71c45e4355f16adbb9e081565fcc94960a9b1a6356b9121b746bd0346f6375",
          "sha1": "18d842bab4fb424d61c8eba8a755aa5124615f2c",
          "md5": "fbcf8d210524c94fe0038b292cfc32fc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "terminal-tablet-1.0.31-javadoc.jar",
          "url": "terminal-tablet-1.0.31-javadoc.jar",
          "size": 412280,
          "sha512": "077d6c46e23a3974fa7822b433dd067bb2c731815c92ddd1306531c66b72820217000a181360dd549fbfea64f1d623fc43d5db8fe276073ed1459e41060a7086",
          "sha256": "7a51007a0f161481dde81ef08d8f798d09ae94c3ab73f7324226b1d1402c5945",
          "sha1": "7eba23ffc924ebcf5f4317df6288b4c83d695f7b",
          "md5": "d4c7d0894bb46ff2aec73df70172ec94"
        }
      ]
    }
  ]
}
