{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "rkcamera",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "rkcamera-1.0.5.aar",
          "url": "rkcamera-1.0.5.aar",
          "size": 69258,
          "sha512": "cea11282413e8932504ab36b5840e970e8ddc1c2e8833a3e68bfc0a6b22dc771f16246d307c373e782ece9763669f35b5fce97fe602a4ee795daed66a4aa3e51",
          "sha256": "265aa17aa6ec985653f78e2e1818074f46af05e67a06a43e40f5daafd7cb679e",
          "sha1": "5207e9246273bfc5e53230a68fd2703ddef5895c",
          "md5": "4b170ccbd97aee98ea8f8bafa3217476"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "rkcamera-1.0.5.aar",
          "url": "rkcamera-1.0.5.aar",
          "size": 69258,
          "sha512": "cea11282413e8932504ab36b5840e970e8ddc1c2e8833a3e68bfc0a6b22dc771f16246d307c373e782ece9763669f35b5fce97fe602a4ee795daed66a4aa3e51",
          "sha256": "265aa17aa6ec985653f78e2e1818074f46af05e67a06a43e40f5daafd7cb679e",
          "sha1": "5207e9246273bfc5e53230a68fd2703ddef5895c",
          "md5": "4b170ccbd97aee98ea8f8bafa3217476"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rkcamera-1.0.5-javadoc.jar",
          "url": "rkcamera-1.0.5-javadoc.jar",
          "size": 293811,
          "sha512": "3cf38d7397852dbe1678d3005fc86ba62fe6813adfd6e2bef20aa9aab46a2dc897444db7e189240461ac0d3814d6b51088daeebd800c791c9d4c32a739a03890",
          "sha256": "f3041c9f88bd33fdf289f4dc75bf1634808c8b40a1fa9e29f951f8348c1adab7",
          "sha1": "34ccfbb3517ce8f62c81e23fd99836aabbcdffa1",
          "md5": "5d340da7bb8cbb43291119eec84ea90d"
        }
      ]
    }
  ]
}
