{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "terminal-tablet",
    "version": "2.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpcomm",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cputils",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-2.2.1.aar",
          "url": "terminal-tablet-2.2.1.aar",
          "size": 146579,
          "sha512": "d1d8101fc471bd391cd289e72a4685ee9899d9cac870738c0e135976aa43d977308a72351e5f0633a1fad9a5426704c27902dd2f4061394ab9b17e2bf39513dd",
          "sha256": "72f44ca1f82aae0dcb0cae29292eb78cae9ddb1812db100b54a6d53de4fa0831",
          "sha1": "d31fa1e99f9c029728535a5a57e32dda9e58e933",
          "md5": "cb75bd7dac486724dda14bd146edd9a0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpcomm",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cputils",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-2.2.1.aar",
          "url": "terminal-tablet-2.2.1.aar",
          "size": 146579,
          "sha512": "d1d8101fc471bd391cd289e72a4685ee9899d9cac870738c0e135976aa43d977308a72351e5f0633a1fad9a5426704c27902dd2f4061394ab9b17e2bf39513dd",
          "sha256": "72f44ca1f82aae0dcb0cae29292eb78cae9ddb1812db100b54a6d53de4fa0831",
          "sha1": "d31fa1e99f9c029728535a5a57e32dda9e58e933",
          "md5": "cb75bd7dac486724dda14bd146edd9a0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "terminal-tablet-2.2.1-javadoc.jar",
          "url": "terminal-tablet-2.2.1-javadoc.jar",
          "size": 447313,
          "sha512": "003223aadf77a80594b41bd5980184b1832d7cad1932d7035f1ffedeafb65ba1d659b32af32efc70d9bbd0cf8265ab5db9e92d92eccbce61547033ea275fc6a4",
          "sha256": "4c357bb4928f701455817d2fb950802674d85315ba3fa4e3bb7e1c6eb8dff579",
          "sha1": "a5e9db6dc82f6a571348d8a77a2face54cf1535c",
          "md5": "d9a2f61150d334e4e0ce73113015c887"
        }
      ]
    }
  ]
}
