{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "rkcamera",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "rkcamera-1.0.2.aar",
          "url": "rkcamera-1.0.2.aar",
          "size": 49752,
          "sha512": "0b16a1517e787d8569c0da8166f61d02569733ab6be9c8bb38c77aac0d371ff826ae83006591e2fba05772ff52659c7e333e63596e6e6a94eb37d9de2fb9d9ee",
          "sha256": "064e11e54633af028a14c2a7ea34fb701fa868faa9b8bfa93b6322cffe1ac308",
          "sha1": "f3db4435808fcee4b35e2f69e5967b073b26978f",
          "md5": "fc1bf9ca0228c4afcadd1bdf10b8b83d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "rkcamera-1.0.2.aar",
          "url": "rkcamera-1.0.2.aar",
          "size": 49752,
          "sha512": "0b16a1517e787d8569c0da8166f61d02569733ab6be9c8bb38c77aac0d371ff826ae83006591e2fba05772ff52659c7e333e63596e6e6a94eb37d9de2fb9d9ee",
          "sha256": "064e11e54633af028a14c2a7ea34fb701fa868faa9b8bfa93b6322cffe1ac308",
          "sha1": "f3db4435808fcee4b35e2f69e5967b073b26978f",
          "md5": "fc1bf9ca0228c4afcadd1bdf10b8b83d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rkcamera-1.0.2-javadoc.jar",
          "url": "rkcamera-1.0.2-javadoc.jar",
          "size": 288386,
          "sha512": "d5ce3c43d08eb6913be5a62d904ebac93e9a47aa3f0b4306e898c7b3e5f738cee99ce57042da7c15418f3a708c71addc802dcf45d02710becae97f40cdbfd368",
          "sha256": "6c978100f69990720ff9f6630edae613ec57e64ab8dd8e92053d88f42d08ea50",
          "sha1": "4136bd5dcf474ac070cefd3c4676dbf0268cc2b1",
          "md5": "370b694c8e76e7b7043502ada8d7342a"
        }
      ]
    }
  ]
}
