{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "terminal-tablet",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpcomm",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cputils",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-2.1.0.aar",
          "url": "terminal-tablet-2.1.0.aar",
          "size": 131606,
          "sha512": "1ec6b8fc99b72077e9b05f9abb1e127d05d089094b3b45874c66e4fbec3913442bff4e70fd637767920bbdf945bdfabe9d27073547bb35c4e0946aaa0425e1ca",
          "sha256": "afd1f9ceadf75517a54239d7e64859922d3db6c35f7ea4e03904026a6101c749",
          "sha1": "81ec0b43adc3ace37ba83d2d718c0f62de28a358",
          "md5": "0bba42d8ab986f8ef79a6547c0b1b92d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpcomm",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cputils",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-2.1.0.aar",
          "url": "terminal-tablet-2.1.0.aar",
          "size": 131606,
          "sha512": "1ec6b8fc99b72077e9b05f9abb1e127d05d089094b3b45874c66e4fbec3913442bff4e70fd637767920bbdf945bdfabe9d27073547bb35c4e0946aaa0425e1ca",
          "sha256": "afd1f9ceadf75517a54239d7e64859922d3db6c35f7ea4e03904026a6101c749",
          "sha1": "81ec0b43adc3ace37ba83d2d718c0f62de28a358",
          "md5": "0bba42d8ab986f8ef79a6547c0b1b92d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "terminal-tablet-2.1.0-javadoc.jar",
          "url": "terminal-tablet-2.1.0-javadoc.jar",
          "size": 424844,
          "sha512": "670fb3b687ed4e1f7b891ac56d8a3729bba485e0e6d80760d31d8a6a5b853dcbcc08047adbd6c5cf3c703894fe814edaa0110a095591823c4bc0f44a8ba9082d",
          "sha256": "60f635dd7de4eb4f105dc6fde7a5a75a46d3bf31c4c26e7ed9036d24410c14d1",
          "sha1": "23265a0cf03f893a2276fcd2b6bf6933e8a4cf2e",
          "md5": "f4edb21f3e2da3922a5ee12bbdedf86d"
        }
      ]
    }
  ]
}
