{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "rkcamera",
    "version": "1.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "rkcamera-1.0.10.aar",
          "url": "rkcamera-1.0.10.aar",
          "size": 80750,
          "sha512": "551b05ad464da8b2d728653f922fc38b720d4b125470b562d558382a03a8484b5300451b53335689183df522bda98a5bc7f30c9bc5aca6ebf4ae9b6e5ad41dce",
          "sha256": "769e5f25ce446b2a49c507c9a54fb054b1868de0502340e20efdb1ed1305353f",
          "sha1": "93c6cc80b8843cdd81d8612dd19ee1e35475ee78",
          "md5": "3df632051efbe06254d61c8a4c5f0e75"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "rkcamera-1.0.10.aar",
          "url": "rkcamera-1.0.10.aar",
          "size": 80750,
          "sha512": "551b05ad464da8b2d728653f922fc38b720d4b125470b562d558382a03a8484b5300451b53335689183df522bda98a5bc7f30c9bc5aca6ebf4ae9b6e5ad41dce",
          "sha256": "769e5f25ce446b2a49c507c9a54fb054b1868de0502340e20efdb1ed1305353f",
          "sha1": "93c6cc80b8843cdd81d8612dd19ee1e35475ee78",
          "md5": "3df632051efbe06254d61c8a4c5f0e75"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rkcamera-1.0.10-javadoc.jar",
          "url": "rkcamera-1.0.10-javadoc.jar",
          "size": 295080,
          "sha512": "584b5c3fff488f07664c15b1093190494270e0ea6e95f789f8d931fe23631cadb4780376523cd374e7f8080faf9f1a48371e08863ca9e632556715e8c1270527",
          "sha256": "d32dc8202c261d898390c9e1799c93a883da5153287b54ffd8a33b269c433c4e",
          "sha1": "cd0b69abbafeee34c2464f348d51cc79e0fa8b1a",
          "md5": "303fe4f94209ae170a0cfde51379e2fc"
        }
      ]
    }
  ]
}
