{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "rkcamera",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "rkcamera-1.0.0.aar",
          "url": "rkcamera-1.0.0.aar",
          "size": 36332,
          "sha512": "871e48463f5db6fbf9cb6956fbb25f638b26498ac0ea429d10fe60d9a5c720ef9da0e199f7c4953e70ba0121f74eaee7689a8fc7ac32d49432c4a4025467627f",
          "sha256": "7fc694632dde826d462749c2ab87a6e309a08ae05aa3cbcf48aba760b960e7c8",
          "sha1": "b1e9d56bed5b9d4a3211d103aa66790b9644233c",
          "md5": "795581dc457845b7c70b53d503008d33"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "rkcamera-1.0.0.aar",
          "url": "rkcamera-1.0.0.aar",
          "size": 36332,
          "sha512": "871e48463f5db6fbf9cb6956fbb25f638b26498ac0ea429d10fe60d9a5c720ef9da0e199f7c4953e70ba0121f74eaee7689a8fc7ac32d49432c4a4025467627f",
          "sha256": "7fc694632dde826d462749c2ab87a6e309a08ae05aa3cbcf48aba760b960e7c8",
          "sha1": "b1e9d56bed5b9d4a3211d103aa66790b9644233c",
          "md5": "795581dc457845b7c70b53d503008d33"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rkcamera-1.0.0-javadoc.jar",
          "url": "rkcamera-1.0.0-javadoc.jar",
          "size": 274981,
          "sha512": "1c411c74de3fc769896401af27cb809c1f02e40e56a9f275e7efde8aa41c45166783b426054b80455942704202ec0358976002e56e3fb868c683127c7283c024",
          "sha256": "a57c86dcbb72465f20017c5b84552ba4aca1beddf6ab5f96344b223008f99f18",
          "sha1": "0a61c54e1f1cd120ab4001ef75a44d2b79e08a83",
          "md5": "ebaf4776db7de56c5e7f39db42d778b8"
        }
      ]
    }
  ]
}
