{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "terminal-tablet",
    "version": "1.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpsdk-cpcomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-1.0.16.aar",
          "url": "terminal-tablet-1.0.16.aar",
          "size": 103158,
          "sha512": "86481772b5908b878387d92994f6fddc733876a80784fe9cedb41e9aabe62317df5572cf2d79eec02d59abec1990b94ca9b7dc231487bf6319cb41f52c021021",
          "sha256": "72e89d0c603afc2cae9b7c8cc8053eeba490d585ae59a4360b1380c6facf6abd",
          "sha1": "8d15f682618fc8bd1689bf261d8546680bc0a0d1",
          "md5": "b34c3df98e0a5fdf3929d9b8e859f7d8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpsdk-cpcomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-1.0.16.aar",
          "url": "terminal-tablet-1.0.16.aar",
          "size": 103158,
          "sha512": "86481772b5908b878387d92994f6fddc733876a80784fe9cedb41e9aabe62317df5572cf2d79eec02d59abec1990b94ca9b7dc231487bf6319cb41f52c021021",
          "sha256": "72e89d0c603afc2cae9b7c8cc8053eeba490d585ae59a4360b1380c6facf6abd",
          "sha1": "8d15f682618fc8bd1689bf261d8546680bc0a0d1",
          "md5": "b34c3df98e0a5fdf3929d9b8e859f7d8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "terminal-tablet-1.0.16-javadoc.jar",
          "url": "terminal-tablet-1.0.16-javadoc.jar",
          "size": 407177,
          "sha512": "fb60aa75346a1ed109f77f51e8b3c6aab334637b34b69131186670b856bf53ec619680a57d7ee66d5599a6e3943f3fc146d2609a3bf295c5e32bb3d29bfc0017",
          "sha256": "f037a4a70fae24c8b711552d91ee34daa98ef118ee01cf6c1a19ffd38b4c139a",
          "sha1": "b2c74a255f0309ca43c935c3f9bc6d430edd878c",
          "md5": "8229fa2d855661870a9ec46737256fa3"
        }
      ]
    }
  ]
}
