{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "terminal-tablet",
    "version": "2.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpcomm",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cputils",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-2.0.3.aar",
          "url": "terminal-tablet-2.0.3.aar",
          "size": 129719,
          "sha512": "dc5db8aa600d6b095f1f46f3eab13ca2c6b3e8e528cf2c092cc0be8b9c2f0aff69ce6cfe50084f8e120fa8edd0ec2135b4c435a930ea876433ac70f406be5868",
          "sha256": "200a8e0c776270e8f3bbc7e7a87fc7a601bea556847f42320ca8b7013ab1f401",
          "sha1": "d73c83f46a6f7e196f76db8a2d165adc619cec71",
          "md5": "27e685a155c4b1a32916f3d4526c21ef"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpcomm",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cputils",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-2.0.3.aar",
          "url": "terminal-tablet-2.0.3.aar",
          "size": 129719,
          "sha512": "dc5db8aa600d6b095f1f46f3eab13ca2c6b3e8e528cf2c092cc0be8b9c2f0aff69ce6cfe50084f8e120fa8edd0ec2135b4c435a930ea876433ac70f406be5868",
          "sha256": "200a8e0c776270e8f3bbc7e7a87fc7a601bea556847f42320ca8b7013ab1f401",
          "sha1": "d73c83f46a6f7e196f76db8a2d165adc619cec71",
          "md5": "27e685a155c4b1a32916f3d4526c21ef"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "terminal-tablet-2.0.3-javadoc.jar",
          "url": "terminal-tablet-2.0.3-javadoc.jar",
          "size": 424756,
          "sha512": "c248889ff75ca00b7c5629ba90a6b4c799af6ac005fafb9bd02c11f25e81d43281fdf39dfda10950687f91b674bd17d0cd2d2bc0d46cfda82e689a0840fca61a",
          "sha256": "862d690acd167b03d409f9b0f39dbb9a83843cf0bfd4ef456d1b7a3bf52aed05",
          "sha1": "ce07c9f1629f76ff8e0d618da4a9a5167de9c027",
          "md5": "e1bca2fb77d47738e525978b57acc671"
        }
      ]
    }
  ]
}
