{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib.cpdevice",
    "module": "apollocomm",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "apollocomm-1.0.2.aar",
          "url": "apollocomm-1.0.2.aar",
          "size": 26197,
          "sha512": "9be8a0b300f11009b59371cffe49bfc3cb057f52eac2c077f18274ecb336a72de419658bbb4c2dffe83934fb1f0ffec2ac2bbb6d59c819b79e59f2a7fcd1c195",
          "sha256": "e6ed7c5b9df5d9b9a191fcc77d695d1fb842bf808b2086aa663281edd791c56f",
          "sha1": "56e333fe224a2c0b98a1ef26ef6fa5aac2cc48a2",
          "md5": "3f11827b7ea1e9b0fa3bc4adbefab345"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "apollocomm-1.0.2.aar",
          "url": "apollocomm-1.0.2.aar",
          "size": 26197,
          "sha512": "9be8a0b300f11009b59371cffe49bfc3cb057f52eac2c077f18274ecb336a72de419658bbb4c2dffe83934fb1f0ffec2ac2bbb6d59c819b79e59f2a7fcd1c195",
          "sha256": "e6ed7c5b9df5d9b9a191fcc77d695d1fb842bf808b2086aa663281edd791c56f",
          "sha1": "56e333fe224a2c0b98a1ef26ef6fa5aac2cc48a2",
          "md5": "3f11827b7ea1e9b0fa3bc4adbefab345"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "apollocomm-1.0.2-javadoc.jar",
          "url": "apollocomm-1.0.2-javadoc.jar",
          "size": 351020,
          "sha512": "c690d8da6f86320618fb4f73127f606a9f5c2c5e95e426882b7ce43a5e92be02fad10152b5b25e80129f58e37edd2a5e35c29ef4655adbb0ee05c99db22eaa66",
          "sha256": "f48830f78ba843ed7195cbbb05b7eaefa0978a72390915c7b9f911e19a93da99",
          "sha1": "834184b5e3de266d7ff0633007a073b97ab9d3c3",
          "md5": "f728acc0c9deed29fa73fc06f6584c0f"
        }
      ]
    }
  ]
}
