{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "rkcamera",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia.ipcam",
          "version": {
            "requires": "2.0.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "rkcamera-1.1.0.aar",
          "url": "rkcamera-1.1.0.aar",
          "size": 103966,
          "sha512": "30db2dff261e501b0a937a50fe4304fd4645e868ab7d569b8bbcc83b06137b2b21172f4c17b17c44c86f8c38b263156174198ab645afe381f24035ffb889bfc8",
          "sha256": "356a329f48cb478b0fb1998896f41575543b6ea9cf726be1df5288ffdf6e3bed",
          "sha1": "8b9f9fa8153a4bde08db111debf7f91ed3e5ac1b",
          "md5": "e66d91472f43695091656866b1a85e82"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.19.1"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia.ipcam",
          "version": {
            "requires": "2.0.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "rkcamera-1.1.0.aar",
          "url": "rkcamera-1.1.0.aar",
          "size": 103966,
          "sha512": "30db2dff261e501b0a937a50fe4304fd4645e868ab7d569b8bbcc83b06137b2b21172f4c17b17c44c86f8c38b263156174198ab645afe381f24035ffb889bfc8",
          "sha256": "356a329f48cb478b0fb1998896f41575543b6ea9cf726be1df5288ffdf6e3bed",
          "sha1": "8b9f9fa8153a4bde08db111debf7f91ed3e5ac1b",
          "md5": "e66d91472f43695091656866b1a85e82"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rkcamera-1.1.0-javadoc.jar",
          "url": "rkcamera-1.1.0-javadoc.jar",
          "size": 310330,
          "sha512": "f9b6491413d36d075bde18f63a070bfadbfb274528f7a9a1b01bf8cca07e78d87067eee15c703f56cfc4161d35369b32e40cf54af37abf9a2c02584952a50b35",
          "sha256": "188e648011d19744bb25dde80c7332611aed903ab6c0cb69d139d5a1fd9d63cc",
          "sha1": "b6434cacdf9ec33a5ccc8007580972b9dd45bd3c",
          "md5": "5b9e91cf9b921ce799784c7f27b4fcdf"
        }
      ]
    }
  ]
}
