{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "terminal-tablet",
    "version": "2.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpcomm",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cputils",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-2.2.5.aar",
          "url": "terminal-tablet-2.2.5.aar",
          "size": 140284,
          "sha512": "5eb973a0bd3ac44cc3f22d6c19ee251a4c3cbd98cd3af53159fad95fe97543bea5d981ec73220da309bc613e21bb073ec906fcd3c2b72ec9c057753d392ebf73",
          "sha256": "ce6360685699693ba5c44ee3f1ac7d0df67a83016e8366ec6c98a5678a2cf5df",
          "sha1": "fff7f7938be968e7a1f57e918620d8f40f909f09",
          "md5": "805504ac680d5ba5e9d51e4ddb4a3dad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpcomm",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cputils",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-2.2.5.aar",
          "url": "terminal-tablet-2.2.5.aar",
          "size": 140284,
          "sha512": "5eb973a0bd3ac44cc3f22d6c19ee251a4c3cbd98cd3af53159fad95fe97543bea5d981ec73220da309bc613e21bb073ec906fcd3c2b72ec9c057753d392ebf73",
          "sha256": "ce6360685699693ba5c44ee3f1ac7d0df67a83016e8366ec6c98a5678a2cf5df",
          "sha1": "fff7f7938be968e7a1f57e918620d8f40f909f09",
          "md5": "805504ac680d5ba5e9d51e4ddb4a3dad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "terminal-tablet-2.2.5-javadoc.jar",
          "url": "terminal-tablet-2.2.5-javadoc.jar",
          "size": 447313,
          "sha512": "003223aadf77a80594b41bd5980184b1832d7cad1932d7035f1ffedeafb65ba1d659b32af32efc70d9bbd0cf8265ab5db9e92d92eccbce61547033ea275fc6a4",
          "sha256": "4c357bb4928f701455817d2fb950802674d85315ba3fa4e3bb7e1c6eb8dff579",
          "sha1": "a5e9db6dc82f6a571348d8a77a2face54cf1535c",
          "md5": "d9a2f61150d334e4e0ce73113015c887"
        }
      ]
    }
  ]
}
