{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "rkcamera",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "rkcamera-1.0.6.aar",
          "url": "rkcamera-1.0.6.aar",
          "size": 70859,
          "sha512": "23f73b5072135ca835aecf6235b1f9b76feb2af2e260aac27c8b108774c9fe9ca523f3815df012cebb1724d4f112725a729a24d9374aa7e4e749ffb879aff9fc",
          "sha256": "074c091919e859581a1fe00a1f8ab46238b6e985a9991f2886f0ce9278dc78f1",
          "sha1": "3beb4cfe647680a83f430655a06799089518b8a6",
          "md5": "146d6f28be03090f1c292f1508b8b69d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "rkcamera-1.0.6.aar",
          "url": "rkcamera-1.0.6.aar",
          "size": 70859,
          "sha512": "23f73b5072135ca835aecf6235b1f9b76feb2af2e260aac27c8b108774c9fe9ca523f3815df012cebb1724d4f112725a729a24d9374aa7e4e749ffb879aff9fc",
          "sha256": "074c091919e859581a1fe00a1f8ab46238b6e985a9991f2886f0ce9278dc78f1",
          "sha1": "3beb4cfe647680a83f430655a06799089518b8a6",
          "md5": "146d6f28be03090f1c292f1508b8b69d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rkcamera-1.0.6-javadoc.jar",
          "url": "rkcamera-1.0.6-javadoc.jar",
          "size": 295006,
          "sha512": "08c3fcafc54ec9ea719942106f0bbeeb1b6ab6cdbf0f27a9545adddaacd89a6224c82df7c3615a24d84e1e28eab632986aeeda87569d3822f73f27f44a0216cd",
          "sha256": "3d292ee9eccb93c6cfe8437adca7256babe87f288538e2e95bc6d30738f9965b",
          "sha1": "a4a290ec2b78606c47b93d2b8c153e193e6bce8b",
          "md5": "4179fef82fe13586d51236fe60e752ac"
        }
      ]
    }
  ]
}
