{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "terminal-tablet",
    "version": "1.0.14.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpsdk-cpcomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-1.0.14.1.aar",
          "url": "terminal-tablet-1.0.14.1.aar",
          "size": 95454,
          "sha512": "340ede40e12050b07ca353d638b88625da19884bdcfbe2d3a6f4963c80837920dca723f9e11a19658e8e99b1584979add9537cdf43d492ef758164ecb392155f",
          "sha256": "98a7677d0df63ef0fc93119d534faf2925a337cccb68478f55e204eb41f981c2",
          "sha1": "551469dc0a245ee9ce4f72aa714a0b563c856037",
          "md5": "2e506d00fbd45437c128932eff77e644"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpsdk-cpcomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-1.0.14.1.aar",
          "url": "terminal-tablet-1.0.14.1.aar",
          "size": 95454,
          "sha512": "340ede40e12050b07ca353d638b88625da19884bdcfbe2d3a6f4963c80837920dca723f9e11a19658e8e99b1584979add9537cdf43d492ef758164ecb392155f",
          "sha256": "98a7677d0df63ef0fc93119d534faf2925a337cccb68478f55e204eb41f981c2",
          "sha1": "551469dc0a245ee9ce4f72aa714a0b563c856037",
          "md5": "2e506d00fbd45437c128932eff77e644"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "terminal-tablet-1.0.14.1-sources.jar",
          "url": "terminal-tablet-1.0.14.1-sources.jar",
          "size": 36134,
          "sha512": "9655fb87e81aebff2db942818fba8b4cdcbc1f6729e4e710e8f36a5d5a976095071c90979225692d50a2a2d0b803f60edfbb5a9bf4de74865514ca6835c9f6aa",
          "sha256": "99c87eb7ec673e153dcf52d2ea022316a6cddfe7dc43b0d18a5c0b7234428a97",
          "sha1": "327390c8db2788f69c63e775beca3de3fea6a09a",
          "md5": "5b1f5b4df87adcb4fecb28b3190200d1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "terminal-tablet-1.0.14.1-javadoc.jar",
          "url": "terminal-tablet-1.0.14.1-javadoc.jar",
          "size": 402719,
          "sha512": "09f314f7aab41e42ce1fd3455a1f2f6c0e50919ae06739d05e3e2bc803e0e2f6db64e5bc570a05f5471195d456721250da70a171efa349823fa6b10c84316406",
          "sha256": "5fe921671fbc4714f5d2fc48038d94fee1483bb12d4a688b2d0ddba25347ecb7",
          "sha1": "48a713a80b33ac92bf7dbc07ea19e68bc59ca56a",
          "md5": "13ed1b3c36f204029605bb407083d827"
        }
      ]
    }
  ]
}
