{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "rkcamera",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "rkcamera-1.0.9.aar",
          "url": "rkcamera-1.0.9.aar",
          "size": 77895,
          "sha512": "1a7c3b068f62357f418fa1fadb877ac2a8abef92be075b577920e63cfff3f29c45d2c7748a11dc1727394cf70d7ef20935dd877e26627f79eb223fd74583c25a",
          "sha256": "294ed9205f97432475cd0b2531689e71632e8bbb2d6e40ab8b8b17268239212a",
          "sha1": "2ae915260396c0c2be6a4cad1154240126660f25",
          "md5": "1338574ef8b1f1901429a61e027f8b5c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "rkcamera-1.0.9.aar",
          "url": "rkcamera-1.0.9.aar",
          "size": 77895,
          "sha512": "1a7c3b068f62357f418fa1fadb877ac2a8abef92be075b577920e63cfff3f29c45d2c7748a11dc1727394cf70d7ef20935dd877e26627f79eb223fd74583c25a",
          "sha256": "294ed9205f97432475cd0b2531689e71632e8bbb2d6e40ab8b8b17268239212a",
          "sha1": "2ae915260396c0c2be6a4cad1154240126660f25",
          "md5": "1338574ef8b1f1901429a61e027f8b5c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rkcamera-1.0.9-javadoc.jar",
          "url": "rkcamera-1.0.9-javadoc.jar",
          "size": 288294,
          "sha512": "d7276e4f1693a54f0d1e3bc6910b6d54218cdf35ce79fb856c3023c0fbbae2ebb248d8030c36bb1c8e9434cba2211fc948499b38adc946999ca6fb8219bfddf8",
          "sha256": "a77a02f19a712bc4eba993c1802fb5d41200e1438a098dcc63b5d25f42b947bf",
          "sha1": "487965ca8166e53e9933a72d593dcdcdaaf97fac",
          "md5": "aad50b337eaafee4533ffb0575e27a95"
        }
      ]
    }
  ]
}
