{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "terminal-tablet",
    "version": "1.0.14.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpsdk-cpcomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-1.0.14.4.aar",
          "url": "terminal-tablet-1.0.14.4.aar",
          "size": 95111,
          "sha512": "d1ff26c7c741e465da981f047643bdee1465953f778c39f1dfed7b5c6d119eca1961f36e64fc25fc0f6c2443268538a9c7a083521ac4403150a19cff06d525dc",
          "sha256": "88121d8d03bc27ce87981cb14356895d1741f07d1157b6996f72681ed73ea899",
          "sha1": "16a6477498f4509c0645753b079897c694be73f5",
          "md5": "a987e6c215948ce124eaf1d79f0d6817"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpsdk-cpcomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-1.0.14.4.aar",
          "url": "terminal-tablet-1.0.14.4.aar",
          "size": 95111,
          "sha512": "d1ff26c7c741e465da981f047643bdee1465953f778c39f1dfed7b5c6d119eca1961f36e64fc25fc0f6c2443268538a9c7a083521ac4403150a19cff06d525dc",
          "sha256": "88121d8d03bc27ce87981cb14356895d1741f07d1157b6996f72681ed73ea899",
          "sha1": "16a6477498f4509c0645753b079897c694be73f5",
          "md5": "a987e6c215948ce124eaf1d79f0d6817"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "terminal-tablet-1.0.14.4-sources.jar",
          "url": "terminal-tablet-1.0.14.4-sources.jar",
          "size": 36200,
          "sha512": "f0fb8e1e8f04b7dcf54f789bdd1bb332dfda3de6a82b96114185b17790677b40eda253f3cd5c90dab81537927bbe4519c116b21039e21bda1e11c8add5dbd19a",
          "sha256": "03f8a67fc88b8c2ac3ea711e87d7519f819371b17f6600cc1700b89699bca5c4",
          "sha1": "ed5a8db971cb518ac95f3aa837853639debdc18e",
          "md5": "0ccfaa17d4b2d2f826eda70c06c45d29"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "terminal-tablet-1.0.14.4-javadoc.jar",
          "url": "terminal-tablet-1.0.14.4-javadoc.jar",
          "size": 402719,
          "sha512": "09f314f7aab41e42ce1fd3455a1f2f6c0e50919ae06739d05e3e2bc803e0e2f6db64e5bc570a05f5471195d456721250da70a171efa349823fa6b10c84316406",
          "sha256": "5fe921671fbc4714f5d2fc48038d94fee1483bb12d4a688b2d0ddba25347ecb7",
          "sha1": "48a713a80b33ac92bf7dbc07ea19e68bc59ca56a",
          "md5": "13ed1b3c36f204029605bb407083d827"
        }
      ]
    }
  ]
}
