{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "terminal-tablet",
    "version": "1.0.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpsdk-cpcomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-1.0.18.aar",
          "url": "terminal-tablet-1.0.18.aar",
          "size": 103339,
          "sha512": "e610c196a87c8da8f763545e82f08da1431bcae7ed193f5b510cd5e6b05fecdd9b573cee6d2a510df36db80a6151f4d88f735c4a50db77faaafdc9aebb360a58",
          "sha256": "1b91dd26785bbdbf60470aabf125514ead1db22ad4f6b2ef585dade35c555e30",
          "sha1": "33f8907a179db2075896a780a8af0e404ff45956",
          "md5": "050c1ee92d502f517a3ec19b0b36ccb4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpsdk-cpcomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-1.0.18.aar",
          "url": "terminal-tablet-1.0.18.aar",
          "size": 103339,
          "sha512": "e610c196a87c8da8f763545e82f08da1431bcae7ed193f5b510cd5e6b05fecdd9b573cee6d2a510df36db80a6151f4d88f735c4a50db77faaafdc9aebb360a58",
          "sha256": "1b91dd26785bbdbf60470aabf125514ead1db22ad4f6b2ef585dade35c555e30",
          "sha1": "33f8907a179db2075896a780a8af0e404ff45956",
          "md5": "050c1ee92d502f517a3ec19b0b36ccb4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "terminal-tablet-1.0.18-javadoc.jar",
          "url": "terminal-tablet-1.0.18-javadoc.jar",
          "size": 407271,
          "sha512": "e2c37acbb7435652fe6648c1bfd8f467ff277ff6c8f3ee51a41c7469f35b2f68fe258b2f751e5bb8ad807bd54111cc2e315dd4d4b9cab7c8ff01c9770d816b36",
          "sha256": "605553551f77b9a48105e97a15df3ce2d1929d862709225e4a5b60930f53aec9",
          "sha1": "3fa9dc81f57c132c7a2d2400af1ec9df8eec26d3",
          "md5": "522ab04fbc1c66783ed9407ec78706e1"
        }
      ]
    }
  ]
}
