{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "terminal-tablet",
    "version": "2.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpcomm",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cputils",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-2.0.6.aar",
          "url": "terminal-tablet-2.0.6.aar",
          "size": 131327,
          "sha512": "f600d8f901bceda2810ff0def35f5ae7aa4697a743242502c43d216d90df0ddd704f52d2aa5b7cdca8986c1053fb2c8ea49d2d00a6b2982ae00f4701d4bd6f34",
          "sha256": "9df6aacc8cbbb6b92ee1152594e6bc89ae3e5b22134355271ae1b1090b350b3f",
          "sha1": "3d7a83b8e1a9b122fc9aed476c763291572f0289",
          "md5": "645c98cdbcb8817aa10e5b3b31e1bff7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpcomm",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cputils",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-2.0.6.aar",
          "url": "terminal-tablet-2.0.6.aar",
          "size": 131327,
          "sha512": "f600d8f901bceda2810ff0def35f5ae7aa4697a743242502c43d216d90df0ddd704f52d2aa5b7cdca8986c1053fb2c8ea49d2d00a6b2982ae00f4701d4bd6f34",
          "sha256": "9df6aacc8cbbb6b92ee1152594e6bc89ae3e5b22134355271ae1b1090b350b3f",
          "sha1": "3d7a83b8e1a9b122fc9aed476c763291572f0289",
          "md5": "645c98cdbcb8817aa10e5b3b31e1bff7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "terminal-tablet-2.0.6-javadoc.jar",
          "url": "terminal-tablet-2.0.6-javadoc.jar",
          "size": 424756,
          "sha512": "c248889ff75ca00b7c5629ba90a6b4c799af6ac005fafb9bd02c11f25e81d43281fdf39dfda10950687f91b674bd17d0cd2d2bc0d46cfda82e689a0840fca61a",
          "sha256": "862d690acd167b03d409f9b0f39dbb9a83843cf0bfd4ef456d1b7a3bf52aed05",
          "sha1": "ce07c9f1629f76ff8e0d618da4a9a5167de9c027",
          "md5": "e1bca2fb77d47738e525978b57acc671"
        }
      ]
    }
  ]
}
