{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "terminal-tablet",
    "version": "2.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpcomm",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cputils",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-2.2.8.aar",
          "url": "terminal-tablet-2.2.8.aar",
          "size": 142186,
          "sha512": "c78680289faa2d4c485bd9191083990b1fb66808c59a7ab3d597950bb91aa8d6fcf223ad594c18f42105c96c53562f14366970012449802a80d8d322ae3d888a",
          "sha256": "da641df6842e35cc4978d431eda4c7ad41aed72a094bef1c5dd1e1897d5b4ed9",
          "sha1": "3223afebabbd913ae4586564619c10f0ac484d37",
          "md5": "1253b6dd403bbd9eaaa940126c4a959e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpcomm",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpbase",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cputils",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "cpmedia",
          "version": {
            "requires": "2.0.4.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-2.2.8.aar",
          "url": "terminal-tablet-2.2.8.aar",
          "size": 142186,
          "sha512": "c78680289faa2d4c485bd9191083990b1fb66808c59a7ab3d597950bb91aa8d6fcf223ad594c18f42105c96c53562f14366970012449802a80d8d322ae3d888a",
          "sha256": "da641df6842e35cc4978d431eda4c7ad41aed72a094bef1c5dd1e1897d5b4ed9",
          "sha1": "3223afebabbd913ae4586564619c10f0ac484d37",
          "md5": "1253b6dd403bbd9eaaa940126c4a959e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "terminal-tablet-2.2.8-javadoc.jar",
          "url": "terminal-tablet-2.2.8-javadoc.jar",
          "size": 450655,
          "sha512": "3734678844816590ec9df819d32c4777505f3dd7ef2d5f0f86b1aa9f71e8263d4dfb13081a6b08065ece1ec5439aa761c7c8852120904c43bf1411823c380ffd",
          "sha256": "1c8fe557ef831f304a9d41f67b2b579283aed28197c0ebb82297f59ea51f3daf",
          "sha1": "437f43e9d03ecb82840a89276d6f31c646ec7bfd",
          "md5": "11c59b2ca459a71ac6d6affc3670a164"
        }
      ]
    }
  ]
}
