{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omsi.lib",
    "module": "terminal-tablet",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "springcomm",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-1.0.9.aar",
          "url": "terminal-tablet-1.0.9.aar",
          "size": 52620,
          "sha512": "3aeb362f037be3f71a6096ea4d0df4c0bbd7a5d6af6974602161c7165915360a50099f87cee928a771458d2ac77ab96101ecf614b647d82439c060648f4e3f3e",
          "sha256": "27697af1a5398e5a353a4354920361087ae2f78b0ec111514a268065cad50933",
          "sha1": "2893d211dcc9fa72b52616695b82ea2cd6effd1f",
          "md5": "768f3243b0b3191cdd25550039979a6a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocamera",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "springcomm",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apolloprocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.omsi.lib.cpdevice",
          "module": "apollocomm",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "terminal-tablet-1.0.9.aar",
          "url": "terminal-tablet-1.0.9.aar",
          "size": 52620,
          "sha512": "3aeb362f037be3f71a6096ea4d0df4c0bbd7a5d6af6974602161c7165915360a50099f87cee928a771458d2ac77ab96101ecf614b647d82439c060648f4e3f3e",
          "sha256": "27697af1a5398e5a353a4354920361087ae2f78b0ec111514a268065cad50933",
          "sha1": "2893d211dcc9fa72b52616695b82ea2cd6effd1f",
          "md5": "768f3243b0b3191cdd25550039979a6a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "terminal-tablet-1.0.9-sources.jar",
          "url": "terminal-tablet-1.0.9-sources.jar",
          "size": 23713,
          "sha512": "26d0282f0ed4da70b4756aca0c819b3b27f6bef2085b276a2ea12b2c25c9e96100e4846c010d8fced78958c2baa9043bc69a8994336197c92f5dcea7aeb14047",
          "sha256": "746fdefe7911214c6a1d37afcd08e1827bc074034d319d62a6059a1a2603c9d1",
          "sha1": "a30ae3eddc209bbfebb71fc0b185a2436bfbb7dc",
          "md5": "42a0e5cf4b111f18c80e551fe4359fa4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "terminal-tablet-1.0.9-javadoc.jar",
          "url": "terminal-tablet-1.0.9-javadoc.jar",
          "size": 369337,
          "sha512": "95759bd85ee711d89da4acdf2ee54add7ee4276ac37b1afc18e5b80023b4b5d440132a50c9f8c9f09207a2f2049a04b46101e355ac542c7d337ae795057f3cc7",
          "sha256": "fad072011e47ee295563e33a6ab059820f4d2214e308eda279eda0044b30f3d7",
          "sha1": "220e7a30825bdddfa83086db73f0c0b0c1f519a9",
          "md5": "c35d0be184fc326ae25f941ae9d2bc3a"
        }
      ]
    }
  ]
}
